# config.ini
[FlowTP_conf]
DENOISER_ESM_MODEL_NAME = ESM2-8M
DENOISER_EMBEDDING = 320
MAX_LENGTH = 50
MIN_LENGTH = 5
SQRT_S = 1e-4
DENOISER_MLP = 320
DIFFUSION_BATCH_SIZE = 64
DENOISER_EPOCH = 680
DENOISER_LR = 1e-3
MIN_DENOISER_LR = 1e-5
DENOISER_CLIP_GRAD = 3
DENOISER_WEIGHT_DECAY = 1e-12
SEED = 42



[temperature_cfs]
avp_temperature_min = 0.6
avp_temperature_max = 1.0
avp_cfs_min = 2.5
avp_cfs_max = 3.0

afp_temperature_min = 0.65
afp_temperature_max = 1
afp_cfs_min = 2.8
afp_cfs_max = 3.5

amp_temperature_min = 0.6
amp_temperature_max = 1.0
amp_cfs_min = 2.5
amp_cfs_max = 3.0


